name: disko
description: A simple app for managing disk space
publish_to: "none"
version: 0.3.3+7

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  macos_ui: ^2.0.9
  elbe: ^0.1.41
  local_hero: ^0.3.0
  file_picker: ^8.1.3
  moewe: ^0.2.7
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^3.0.2
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/icon.png"
