name: disko
description: A simple app for managing disk space
publish_to: 'none'
version: 0.3.2+6

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  macos_ui: ^2.0.2
  logger: ^2.0.2+1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  elbe: ^0.1.30
  path: ^1.8.3
  local_hero: ^0.3.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_oss_licenses: ^2.0.1
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/



flutter_launcher_icons:
  macos:
    generate: true
    image_path: "assets/icon.png"
  